project 'FinanceManager.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinanceManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for FinanceManager
pod 'SWXMLHash', '~> 5.0.0'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
end
